### ISSUE TITLE
langchain支持修改openai的base url吗，国内访问不了，找代码配置貌似没找到

### ISSUE THREAD

**Issue by StephenHuge** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#1]

**Comment by wangfeng35** [comment]
设置了API_BASE但是会包括AttributeError: 'str' object has no attribute 'get'

用官方API就没问题 搞不懂。。。

**Comment by liaokongVFX** [comment]
> 设置了API_BASE但是会包括AttributeError: 'str' object has no attribute 'get'
> 
> 用官方API就没问题 搞不懂。。。

可以贴下代码和具体报错信息

**Comment by wangfeng35** [comment]
> > 设置了API_BASE但是会包括AttributeError: 'str' object has no attribute 'get'
> > 用官方API就没问题 搞不懂。。。
> 
> 可以贴下代码和具体报错信息

找到原因了 langchain的OPENAIEmbeddings用的是旧版engie接口，有的第三方接口不支持旧接口。也不知道langchain什么时候才更新到新接口
