### ISSUE TITLE
转化为document对象出错

### ISSUE THREAD

**Issue by zhangyiw** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#10]
调试代码为document = loader.load()
一直报一下错误：
Exception has occurred: ImportError
cannot import name 'open_filename' from 'pdfminer.utils' (G:\Anaconda\anaconda3\envs\longchain\lib\site-packages\pdfminer\utils.py)
  File "G:\llm_py\gcd_qa.py", line 11, in <module>
    documents = loader.load()
ImportError: cannot import name 'open_filename' from 'pdfminer.utils' (G:\Anaconda\anaconda3\envs\longchain\lib\site-packages\pdfminer\utils.py)

**Comment by AllenLai1216** [comment]
試試 先解除現有的 pdfminer
pip uninstall pdfminer

再安裝 pdfminer.six
pip install pdfminer.six

**Comment by liaokongVFX** [comment]
应该是`pdfminer`包的问题，可以试试楼上大佬的方法~
