### ISSUE TITLE
data文件夹中没有gitbook中提到的测试数据

### ISSUE THREAD

**Issue by BiHong-Yang** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#15]
![image](https://user-images.githubusercontent.com/61420495/236614145-0b004b55-13f0-499a-b7c1-66920c3b94aa.png)
您好，在我使用colab运行试验的时候，发现在data文件夹中没有gitbook里提到的数据

**Comment by liaokongVFX** [comment]
colab貌似没法保存额外文件，科大讯飞那个test.txt你可以随便找个短文章放进去就行了。
lg_test.txt可以用下面这个
https://github.com/liaokongVFX/LangChain-Chinese-Getting-Started-Guide/blob/main/data/lg_test.txt
