### ISSUE TITLE
openai api rate limits

### ISSUE THREAD

**Issue by ivy2315** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#16]
想請問一下，我在跑 "构建本地知识库问答机器人" 時，會碰到以下問題：
`You exceeded your current quota, please check your plan and billing details.`
這是代表我要花錢才能跑嗎？我丟的檔案是很小的 txt 檔。

謝謝！

**Comment by liaokongVFX** [comment]
对的，看样子是你的账号没钱了，需要充值才行。
