### ISSUE TITLE
您好，请问怎么设置 chain 回答是中文，而不是英文

### ISSUE THREAD

**Issue by rongweihe** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#25]
Question: 没想到你是这样的人
Helpful Answer:

> Finished chain.

> Finished chain.
问题: 没想到你是这样的人 回答:  I'm sorry if I disappointed you.

> Entering new StuffDocumentsChain chain...

**Comment by liaokongVFX** [comment]
需要在Prompt中明确的指出，让他使用中文进行回答，可以参考这个问题：https://github.com/liaokongVFX/LangChain-Chinese-Getting-Started-Guide/issues/12
