### ISSUE TITLE
知识库文档机器人咨询

### ISSUE THREAD

**Issue by shiwenwen** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#27]
想做一个知识库文档机器人，但是知识库文档相对比较庞大，载入之后存储向量数据库，使用embeddings时，总是会超出Token限制，如何更好的解决这个问题呢

**Comment by liaokongVFX** [comment]
embeddings时报这个错，一般就是docment太长了。建议再文本切割时，减小chunk_size的值
