### ISSUE TITLE
你们消耗token会很快吗？

### ISSUE THREAD

**Issue by zxdmrg** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#35]
用测试的小说做了一下总结5美刀就用光了

**Comment by SimFG** [comment]
会，看你执行什么请求了。字越多越费钱，日常搭建小工具的话可以尝试了解下[GPTCache](https://github.com/zilliztech/GPTCache)，已经很好集成了langchain

**Comment by zxdmrg** [comment]
好的 感谢
