### ISSUE TITLE
有没有大佬使用php 构建一个本地知识库 对用户上传的文件进行总结回答？

### ISSUE THREAD

**Issue by johnsonwong666** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#37]
我想用pincone向量数据库 但是不知道怎么对源文本进行分段保存

**Comment by liaokongVFX** [comment]
php可用用这个langchain的库 https://github.com/kambo-1st/langchain-php
pincone也提供了restful api，官方也提供了php请求示例 https://docs.pinecone.io/reference/describe_index_stats_post

**Comment by johnsonwong666** [comment]
> langchain
https://github.com/kambo-1st/langchain-php 这个库貌似要 php 8.1  我的是7.4  感觉用不了
