### ISSUE TITLE
langchain的mr chain似乎并不是如图的并发请求,从执行看似乎是依次执行的 最后合并

### ISSUE THREAD

**Issue by jianglanCao** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#43]
![image](https://github.com/liaokongVFX/LangChain-Chinese-Getting-Started-Guide/assets/37798223/3c748b8f-00fa-4525-8207-7db83c509c70)
可以看下langchian的mr chain源码 mr虽然是分而治之
但是似乎langchian的实现上 都是同步代码 每一个doc执行完了后执行下一个 然后reduce
作者可以看看确认下?

**Comment by liaokongVFX** [comment]
每个doc总结是一个一个执行的，并不是同时执行，这里的图只是为了说明每个分割后的doc是单独总结的，并不代表代码执行的顺序。

**Comment by jianglanCao** [comment]
作者知道有异步并发执行的支持吗？
现成的chain之类的
