### ISSUE TITLE
对其他开源大模型的扩展教程

### ISSUE THREAD

**Issue by brizer** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#46]
我仔细看过博主的文章，基本是基于openai的token来完成的langchain的一系列功能。这里想问下，langchain配合其他大语言模型比如说Chinese-LLaMA-Alpaca，作者有没有兴趣也研究下，私有化部署大模型+预训练+langchain的结合，出个教程呢？

**Comment by iluhcm** [comment]
可以参考 https://github.com/imClumsyPanda/langchain-ChatGLM 这个库

**Comment by brizer** [comment]
> https://github.com/imClumsyPanda/langchain-ChatGLM

嗯嗯，谢谢，我现在就是基于这套方案来玩的。
