### ISSUE TITLE
前面几个例子：一问一答，谷歌搜索，问答机器人等可以用 GPT3.5 吗？

### ISSUE THREAD

**Issue by tanteng** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#49]
前面几个例子：一问一答，谷歌搜索，总结，问答机器人等可以用 GPT3.5 模型吗？

比如在前面的几个例子中， llm 如果改成这样返回也不会报错 ：
```
ChatOpenAI(temperature=0.1,max_tokens=2048)
```

效果似乎也好了一些，看文档介绍应该可以，但不知道是不是真的用的 GPT3.5 模型。

以下摘自文档：

```
LLM 调用

支持多种模型接口，比如 OpenAI、Hugging Face、AzureOpenAI ...
```

**Comment by liaokongVFX** [comment]
可以的，`ChatOpenAI` 就是 默认用的就是gpt-3.5-turbo的模型，可参看源码： https://github.com/hwchase17/langchain/blob/83eea230f3f0a3b21caba9917f6e2750445db9f5/langchain/chat_models/openai.py#LL158C5-L158C5
