### ISSUE TITLE
langchain能做基于DB的text2sql吗？

### ISSUE THREAD

**Issue by shangguansb** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#5]
目前基于langchain比较惊艳的使用案例有chatPdf和chatExcel，chatExcel能做基于DS的大数据集（1000万行数据）的text2sql吗？
以及目前还有哪些比较经典的langchain的应用案例，可以分享一下吗？

最后，感谢您的这个项目，这是一个非常赞的项目！

**Comment by liaokongVFX** [comment]
text2sql用openai 的 api就可以实现，只需要写好相应的prompt。
而你可以使用 langchain 实现通过自然语言直接执行连接好的数据库。
我在文档里面加了一个例子，可以在文章中搜索 `通过自然语言生成执行SQL命令` 查看对应的内容。
