### ISSUE TITLE
load_tools 已经不是最新版本能用的了？

### ISSUE THREAD

**Issue by GuanshiyinPusa** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#62]
尝试了
from langchain.agents import load_tools
发现load_tools
ImportError: cannot import name 'load_tools' from 'langchain.agents'
麻烦改一下！谢谢

**Comment by liaokongVFX** [comment]
我刚测了下0.286这个版本是没问题的
![image](https://github.com/liaokongVFX/LangChain-Chinese-Getting-Started-Guide/assets/13622183/4224eb8c-379a-4361-b7cf-28ac49467209)
看了眼源码，也是在`langchain.agents`里导入了`load_tools`
https://github.com/langchain-ai/langchain/blob/02c5c13a6ec8772ed6b898a8ed49e6013b9b4215/libs/langchain/langchain/agents/__init__.py#L61

**Comment by GuanshiyinPusa** [comment]
行，谢谢大佬。第一次issue，好快的反馈
