### ISSUE TITLE
询问关于 ChatGPT 插件相关问题

### ISSUE THREAD

**Issue by YUFEIFUT** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#63]
![image](https://github.com/liaokongVFX/LangChain-Chinese-Getting-Started-Guide/assets/55017929/f5eaa3c1-c86c-46f6-b377-7d55d237d7ce)
我看了一下 langchain 官网上的关于 ChatGPT 插件的例子：
`tool = AIPluginTool.from_plugin_url("https://www.klarna.com/.well-known/ai-plugin.json")`
它主要有一行这个内容，我去 openai 的插件部分的文档上找了一下，没找到其他可以填的 url ，请问博主你知道还可以写哪些其他的 url 嘛

**Comment by liaokongVFX** [comment]
这是个好问题，其实我们可以直接通过在chatgpt中安装插件时，捕获请求就可以看到对应的插件地址。在 user-settings 这个请求中，我们可以看到他的 domain 对应的地址，然后用这个地址去拼接上 `/.well-known/ai-plugin.json` 这个后缀，就是这个插件的完整地址。不过langchain的插件只能调用不需要授权的，在 user-settings 这个请求中，manifest 的 auth type 为 none 就是不需要搜授权的。
