### ISSUE TITLE
langchain设置生成字数

### ISSUE THREAD

**Issue by jiangxiaobin96** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#64]
使用langchain对长文本进行总结，怎么设置生成多少字

**Comment by liaokongVFX** [comment]
可以在prompt中明确的告诉他你的最大字数。不过大语言模型其实对字数是计算不准的，因为大语言模型理解语言的最小单位是 Token，所以返回的字数可能不会很准确。
