### ISSUE TITLE
您好 有个问题

### ISSUE THREAD

**Issue by zach0409** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#7]
非常感谢你的帮助 很有用 我遇到了一个问题   docs = pinecone.similarity_search(prompt, include_metadata=True, k=2)  我这边如果k为默认4的话 有的时候搜索会就报错 This model's maximum context length is 4097 tokens.  k设置2不会有问题 我不知道为什么会出现这个情况

pinecone.init(
    api_key="xxxxxxx",
    environment="xxxxx"
)
index_name = "xxxxxx"
os.environ["OPENAI_API_KEY"] = "XXXXXXXXX"

embeddings = OpenAIEmbeddings(openai_api_key=os.environ['OPENAI_API_KEY'])
pinecone = Pinecone.from_existing_index(index_name, embeddings)
openAI = ChatOpenAI(temperature=0.3, model_name='gpt-3.5-turbo', openai_api_key=os.environ['OPENAI_API_KEY'])
chain = load_qa_chain(openAI, chain_type="stuff")

def askGPT(prompt):
    docs = pinecone.similarity_search(prompt, include_metadata=True, k=4)
    # 使用langchain的load_qa_chain函数加载一个问答链
    ch = chain.run(input_documents=docs, question=prompt)
    return ch

这是我的代码 当k为默认值4的时候会导致报错

**Comment by liaokongVFX** [comment]
每个Document应该是长度太大了，所以再发送给gpt的时候会超过gpt的最大token，要不就是就是再分割文本的时候减小chunk_size的值，要不就只能减少k的数量（k可以理解为最匹配问题的k条）

**Comment by zach0409** [comment]
> 每个Document应该是长度太大了，所以再发送给gpt的时候会超过gpt的最大token，要不就是在分割文档的时候减少小chunk_size的值，要不只是能减少很少k的数量（k可以理解为最匹配问题的k条）

好的 谢谢
