### ISSUE TITLE
一次提问后，agent可以反复调用多个tool吗？

### ISSUE THREAD

**Issue by shangguansb** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#9]
现在感觉每次问问题，就只使用一个tool，有办法像autogpt一样，多次递归调用然后求出最优解吗？
例如：先检索向量数据库，然后谷歌搜索，然后再检索限量数据库，然后读取mysql数据库，然后总结答案。
能方便给一个这样的demo例子吗？往上找不到任何这种相关的例子

**Comment by liaokongVFX** [comment]
可以看下文章中`自定义agent中所使用的工具`这个案例。可以自己去编排要用的tool，并且在`description`参数中通过描述给定每个tool的权重。
